language: go

go:
  - "1.10"

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: ""
      
install:
  - go get -u golang.org/x/lint/golint
  - go get -u gopkg.in/alecthomas/gometalinter.v2

script:
  - java -version

cache:
  directories:
    - '$HOME/.sonar/cache'
